package com.dartmedia.felino.form;
import com.dartmedia.felino.gSqlContainer;
import com.dartmedia.felino.fgetsql;
import com.dartmedia.felino.gSqlContainer;
import com.vaadin.cdi.CDIView;
import com.vaadin.data.fieldgroup.BeanFieldGroup;
import org.vaadin.maddon.fields.MTable;
import com.vaadin.event.LayoutEvents;
import org.vaadin.maddon.layouts.MHorizontalLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.TextField;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.DateField;
import com.vaadin.ui.PopupDateField;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener;
import com.vaadin.data.util.sqlcontainer.query.FreeformQuery;
import javax.annotation.PostConstruct;
import org.vaadin.maddon.label.Header;
import org.vaadin.maddon.layouts.MVerticalLayout;
@CDIView("MyWorkList")
public class MyWorkListView extends MVerticalLayout implements View {
//MyWorkListSvc data=new MyWorkListSvc();
    @PostConstruct
    public void initComponent() {
// @Inject
//TbrandForm form;
/****/
StringBuffer sb = new StringBuffer();
sb.append("");
sb.append("SELECT /* orderreport.xml : custcenter.orderreport.selectMyWorkList by MyWorkList */");
sb.append("         SUM(X.ORDER_CNT) AS ORDER_CNT");
sb.append("       , SUM(X.ORDER_QTY) AS ORDER_QTY");
sb.append("       , SUM(X.ORDER_AMT) AS ORDER_AMT");
sb.append("       , SUM(X.CANCEL_CNT) AS CANCEL_CNT");
sb.append("       , SUM(X.CANCEL_QTY) AS CANCEL_QTY");
sb.append("       , SUM(X.CANCEL_AMT) AS CANCEL_AMT");
sb.append("       , SUM(X.RETURN_CNT) AS RETURN_CNT");
sb.append("       , SUM(X.RETURN_QTY) AS RETURN_QTY");
sb.append("       , SUM(X.RETURN_AMT) AS RETURN_AMT");
sb.append("       , SUM(X.RETURN_CAN_CNT) AS RETURN_CAN_CNT");
sb.append("       , SUM(X.RETURN_CAN_QTY) AS RETURN_CAN_QTY");
sb.append("       , SUM(X.RETURN_CAN_AMT) AS RETURN_CAN_AMT");
sb.append("       , SUM(X.EXCH_CNT) AS EXCH_CNT");
sb.append("       , SUM(X.EXCH_CAN_CNT) AS EXCH_CAN_CNT");
sb.append("       , SUM(X.AS_CNT) AS AS_CNT");
sb.append("       , SUM(X.COUNSEL_CNT) AS COUNSEL_CNT");
sb.append("       , SUM(X.COUNSEL_PROC_CNT) AS COUNSEL_PROC_CNT");
sb.append("       , SUM(X.QUESTION_CNT) AS QUESTION_CNT");
sb.append("       , SUM(X.OB_ALLOC_CNT) AS OB_ALLOC_CNT");
sb.append("       , SUM(X.OB_PROC_CNT) AS OB_PROC_CNT");
sb.append("       , SUM(X.OB_NOPROC_CNT) AS OB_NOPROC_CNT                     ");
sb.append("       , SUM(X.ORDER_QTY)- SUM(X.CANCEL_QTY)- SUM(X.RETURN_QTY)+ SUM(X.RETURN_CAN_QTY) AS TOT_QTY");
sb.append("       , SUM(X.ORDER_AMT)- SUM(X.CANCEL_AMT)- SUM(X.RETURN_AMT)+ SUM(X.RETURN_CAN_AMT) AS TOT_AMT");
sb.append("    FROM (                                                         ");
sb.append("  SELECT COUNT(DISTINCT B.ORDER_NO) AS ORDER_CNT,                                    ");
sb.append("         SUM(B.ORDER_QTY) AS ORDER_QTY,                            ");
sb.append("         SUM(B.ORDER_QTY * B.SALE_PRICE - B.DC_AMT) AS ORDER_AMT,  ");
sb.append("         0 AS CANCEL_CNT,                                          ");
sb.append("         0 AS CANCEL_QTY,                                          ");
sb.append("         0 AS CANCEL_AMT,                                          ");
sb.append("         0 AS RETURN_CNT,                                          ");
sb.append("         0 AS RETURN_QTY,                                          ");
sb.append("         0 AS RETURN_AMT,                                          ");
sb.append("         0 AS RETURN_CAN_CNT,                                      ");
sb.append("         0 AS RETURN_CAN_QTY,                                      ");
sb.append("         0 AS RETURN_CAN_AMT,                                      ");
sb.append("         0 AS EXCH_CNT,                                            ");
sb.append("         0 AS EXCH_CAN_CNT,                                        ");
sb.append("         0 AS AS_CNT,                                              ");
sb.append("         0 AS COUNSEL_CNT,                                         ");
sb.append("         0 AS COUNSEL_PROC_CNT,                                    ");
sb.append("         0 AS QUESTION_CNT,                                        ");
sb.append("         0 AS OB_ALLOC_CNT,                                        ");
sb.append("         0 AS OB_PROC_CNT,                                         ");
sb.append("         0 AS OB_NOPROC_CNT                                        ");
sb.append("    FROM TORDERGOODS B,                                            ");
sb.append("         TORDERM     A                                             ");
sb.append("   WHERE A.ORDER_NO    = B.ORDER_NO");
sb.append("     AND A.INSERT_ID = 'user_id'");
sb.append("     AND A.ORDER_DATE <");
sb.append("[CDATA[>=]]>");
sb.append("TO_DATE('2014-01-01','yyyy/mm/dd')");
sb.append("AND");
sb.append("A.ORDER_DATE");
sb.append("<![CDATA[<");
sb.append("]]>");
sb.append("TO_DATE('2014-01-01','yyyy/mm/dd')");
sb.append("+");
sb.append("1");
sb.append("UNION");
sb.append("ALL");
sb.append("SELECT");
sb.append("0");
sb.append("AS");
sb.append("ORDER_CNT,");
sb.append("0");
sb.append("AS");
sb.append("ORDER_QTY,");
sb.append("0");
sb.append("AS");
sb.append("ORDER_AMT,");
sb.append("COUNT(DISTINCT");
sb.append("A.ORDER_NO||A.ORDER_G_SEQ||TO_CHAR(A.CANCEL_DATE,'YYYYMMDD'))");
sb.append("AS");
sb.append("CANCEL_CNT,");
sb.append("SUM(DECODE(A.ORDER_D_SEQ,");
sb.append("'001',");
sb.append("A.CANCEL_QTY,");
sb.append("0))");
sb.append("AS");
sb.append("CANCEL_QTY,");
sb.append("SUM(A.RSALE_AMT)");
sb.append("AS");
sb.append("CANCEL_AMT,");
sb.append("0");
sb.append("AS");
sb.append("RETURN_CNT,");
sb.append("0");
sb.append("AS");
sb.append("RETURN_QTY,");
sb.append("0");
sb.append("AS");
sb.append("RETURN_AMT,");
sb.append("0");
sb.append("AS");
sb.append("RETURN_CAN_CNT,");
sb.append("0");
sb.append("AS");
sb.append("RETURN_CAN_QTY,");
sb.append("0");
sb.append("AS");
sb.append("RETURN_CAN_AMT,");
sb.append("0");
sb.append("AS");
sb.append("EXCH_CNT,");
sb.append("0");
sb.append("AS");
sb.append("EXCH_CAN_CNT,");
sb.append("0");
sb.append("AS");
sb.append("AS_CNT,");
sb.append("0");
sb.append("AS");
sb.append("COUNSEL_CNT,");
sb.append("0");
sb.append("AS");
sb.append("COUNSEL_PROC_CNT,");
sb.append("0");
sb.append("AS");
sb.append("QUESTION_CNT,");
sb.append("0");
sb.append("AS");
sb.append("OB_ALLOC_CNT,");
sb.append("0");
sb.append("AS");
sb.append("OB_PROC_CNT,");
sb.append("0");
sb.append("AS");
sb.append("OB_NOPROC_CNT");
sb.append("FROM");
sb.append("TORDERPROC");
sb.append("B,");
sb.append("TCANCELDT");
sb.append("A");
sb.append("WHERE");
sb.append("A.ORDER_NO");
sb.append("=");
sb.append("B.ORDER_NO");
sb.append("AND");
sb.append("A.ORDER_G_SEQ");
sb.append("=");
sb.append("B.ORDER_G_SEQ");
sb.append("AND");
sb.append("A.ORDER_D_SEQ");
sb.append("=");
sb.append("B.ORDER_D_SEQ");
sb.append("AND");
sb.append("A.ORDER_W_SEQ");
sb.append("=");
sb.append("B.ORDER_W_SEQ");
sb.append("AND");
sb.append("B.ORDER_P_SEQ");
sb.append("=");
sb.append("'001'");
sb.append("AND");
sb.append("B.PROC_ID");
sb.append("=");
sb.append("'user_id'");
sb.append("AND");
sb.append("A.CANCEL_DATE");
sb.append("<![CDATA[>=]]>");
sb.append("TO_DATE('2014-01-01','yyyy/mm/dd')");
sb.append("AND");
sb.append("A.CANCEL_DATE");
sb.append("<![CDATA[<");
sb.append("]]>");
sb.append("TO_DATE('2014-01-01','yyyy/mm/dd')");
sb.append("+");
sb.append("1");
sb.append("UNION");
sb.append("ALL");
sb.append("SELECT");
sb.append("0");
sb.append("AS");
sb.append("ORDER_CNT,");
sb.append("0");
sb.append("AS");
sb.append("ORDER_QTY,");
sb.append("0");
sb.append("AS");
sb.append("ORDER_AMT,");
sb.append("0");
sb.append("AS");
sb.append("CANCEL_CNT,");
sb.append("0");
sb.append("AS");
sb.append("CANCEL_QTY,");
sb.append("0");
sb.append("AS");
sb.append("CANCEL_AMT,");
sb.append("COUNT(DISTINCT");
sb.append("DECODE(A.CLAIM_GB,");
sb.append("'30',");
sb.append("A.ORDER_NO||A.ORDER_G_SEQ||TO_CHAR(A.CLAIM_DATE,'YYYYMMDD'),");
sb.append("NULL))");
sb.append("AS");
sb.append("RETURN_CNT,");
sb.append("SUM(DECODE(A.CLAIM_GB,");
sb.append("'30',");
sb.append("DECODE(A.ORDER_D_SEQ,");
sb.append("'001',");
sb.append("A.CLAIM_QTY,");
sb.append("0),");
sb.append("0))");
sb.append("AS");
sb.append("RETURN_QTY,");
sb.append("SUM(DECODE(A.CLAIM_GB,");
sb.append("'30',");
sb.append("A.RSALE_AMT))");
sb.append("AS");
sb.append("RETURN_AMT,");
sb.append("COUNT(DISTINCT");
sb.append("DECODE(A.CLAIM_GB,");
sb.append("'31',");
sb.append("A.ORDER_NO||A.ORDER_G_SEQ||TO_CHAR(A.CLAIM_DATE,'YYYYMMDD'),");
sb.append("NULL))");
sb.append("AS");
sb.append("RETURN_CAN_CNT,");
sb.append("SUM(DECODE(A.CLAIM_GB,");
sb.append("'31',");
sb.append("DECODE(A.ORDER_D_SEQ,");
sb.append("'001',");
sb.append("A.CLAIM_QTY,");
sb.append("0),");
sb.append("0))");
sb.append("AS");
sb.append("RETURN_CAN_QTY,");
sb.append("SUM(DECODE(A.CLAIM_GB,");
sb.append("'31',");
sb.append("A.RSALE_AMT))");
sb.append("AS");
sb.append("RETURN_CAN_AMT,");
sb.append("COUNT(DISTINCT");
sb.append("DECODE(A.CLAIM_GB,");
sb.append("'40',");
sb.append("A.ORDER_NO||A.ORDER_G_SEQ||TO_CHAR(A.CLAIM_DATE,'YYYYMMDD'),");
sb.append("NULL))");
sb.append("AS");
sb.append("EXCH_CNT,");
sb.append("COUNT(DISTINCT");
sb.append("DECODE(A.CLAIM_GB,");
sb.append("'41',");
sb.append("A.ORDER_NO||A.ORDER_G_SEQ||TO_CHAR(A.CLAIM_DATE,'YYYYMMDD'),");
sb.append("NULL))");
sb.append("AS");
sb.append("EXCH_CAN_CNT,");
sb.append("COUNT(DISTINCT");
sb.append("DECODE(A.CLAIM_GB,");
sb.append("'50',");
sb.append("A.ORDER_NO||A.ORDER_G_SEQ||TO_CHAR(A.CLAIM_DATE,'YYYYMMDD'),");
sb.append("NULL))");
sb.append("AS");
sb.append("AS_CNT,");
sb.append("0");
sb.append("AS");
sb.append("COUNSEL_CNT,");
sb.append("0");
sb.append("AS");
sb.append("COUNSEL_PROC_CNT,");
sb.append("0");
sb.append("AS");
sb.append("QUESTION_CNT,");
sb.append("0");
sb.append("AS");
sb.append("OB_ALLOC_CNT,");
sb.append("0");
sb.append("AS");
sb.append("OB_PROC_CNT,");
sb.append("0");
sb.append("AS");
sb.append("OB_NOPROC_CNT");
sb.append("FROM");
sb.append("TORDERPROC");
sb.append("B,");
sb.append("TCLAIMDT");
sb.append("A");
sb.append("WHERE");
sb.append("A.ORDER_NO");
sb.append("=");
sb.append("B.ORDER_NO");
sb.append("AND");
sb.append("A.ORDER_G_SEQ");
sb.append("=");
sb.append("B.ORDER_G_SEQ");
sb.append("AND");
sb.append("A.ORDER_D_SEQ");
sb.append("=");
sb.append("B.ORDER_D_SEQ");
sb.append("AND");
sb.append("A.ORDER_W_SEQ");
sb.append("=");
sb.append("B.ORDER_W_SEQ");
sb.append("AND");
sb.append("B.ORDER_P_SEQ");
sb.append("=");
sb.append("'001'");
sb.append("AND");
sb.append("B.PROC_ID");
sb.append("=");
sb.append("'user_id'");
sb.append("AND");
sb.append("A.CLAIM_GB");
sb.append("IN");
sb.append("('30','31','40','41','50')");
sb.append("AND");
sb.append("A.CLAIM_DATE");
sb.append("<![CDATA[>=]]>");
sb.append("TO_DATE('2014-01-01','yyyy/mm/dd')");
sb.append("AND");
sb.append("A.CLAIM_DATE");
sb.append("<![CDATA[<");
sb.append("]]>");
sb.append("TO_DATE('2014-01-01','yyyy/mm/dd')");
sb.append("+");
sb.append("1");
sb.append("UNION");
sb.append("ALL");
sb.append("SELECT");
sb.append("0");
sb.append("AS");
sb.append("ORDER_CNT,");
sb.append("0");
sb.append("AS");
sb.append("ORDER_QTY,");
sb.append("0");
sb.append("AS");
sb.append("ORDER_AMT,");
sb.append("0");
sb.append("AS");
sb.append("CANCEL_CNT,");
sb.append("0");
sb.append("AS");
sb.append("CANCEL_QTY,");
sb.append("0");
sb.append("AS");
sb.append("CANCEL_AMT,");
sb.append("0");
sb.append("AS");
sb.append("RETURN_CNT,");
sb.append("0");
sb.append("AS");
sb.append("RETURN_QTY,");
sb.append("0");
sb.append("AS");
sb.append("RETURN_AMT,");
sb.append("0");
sb.append("AS");
sb.append("RETURN_CAN_CNT,");
sb.append("0");
sb.append("AS");
sb.append("RETURN_CAN_QTY,");
sb.append("0");
sb.append("AS");
sb.append("RETURN_CAN_AMT,");
sb.append("0");
sb.append("AS");
sb.append("EXCH_CNT,");
sb.append("0");
sb.append("AS");
sb.append("EXCH_CAN_CNT,");
sb.append("0");
sb.append("AS");
sb.append("AS_CNT,");
sb.append("COUNT(DISTINCT");
sb.append("DECODE(A.DO_FLAG,");
sb.append("'10',");
sb.append("B.CUST_NO||A.COUNSEL_SEQ,");
sb.append("NULL))");
sb.append("AS");
sb.append("COUNSEL_CNT,");
sb.append("COUNT(DISTINCT");
sb.append("DECODE(A.DO_FLAG,");
sb.append("'10',");
sb.append("NULL,");
sb.append("B.CUST_NO||A.COUNSEL_SEQ||TO_CHAR(A.PROC_DATE,'YYYYMMDD')))");
sb.append("AS");
sb.append("COUNSEL_PROC_CNT,");
sb.append("0");
sb.append("AS");
sb.append("QUESTION_CNT,");
sb.append("0");
sb.append("AS");
sb.append("OB_ALLOC_CNT,");
sb.append("0");
sb.append("AS");
sb.append("OB_PROC_CNT,");
sb.append("0");
sb.append("AS");
sb.append("OB_NOPROC_CNT");
sb.append("FROM");
sb.append("TCUSTCOUNSELDT");
sb.append("A,");
sb.append("TCUSTCOUNSELM");
sb.append("B");
sb.append("WHERE");
sb.append("A.COUNSEL_SEQ");
sb.append("=");
sb.append("B.COUNSEL_SEQ");
sb.append("AND");
sb.append("A.DO_FLAG");
sb.append("IN");
sb.append("('10',");
sb.append("'20',");
sb.append("'30',");
sb.append("'40')");
sb.append("AND");
sb.append("A.PROC_ID");
sb.append("=");
sb.append("'user_id'");
sb.append("AND");
sb.append("A.PROC_DATE");
sb.append("<![CDATA[>=]]>");
sb.append("TO_DATE('2014-01-01','yyyy/mm/dd')");
sb.append("AND");
sb.append("A.PROC_DATE");
sb.append("<![CDATA[<");
sb.append("]]>");
sb.append("TO_DATE('2014-01-01','yyyy/mm/dd')");
sb.append("+");
sb.append("1");
sb.append("UNION");
sb.append("ALL");
sb.append("SELECT");
sb.append("0");
sb.append("AS");
sb.append("ORDER_CNT,");
sb.append("0");
sb.append("AS");
sb.append("ORDER_QTY,");
sb.append("0");
sb.append("AS");
sb.append("ORDER_AMT,");
sb.append("0");
sb.append("AS");
sb.append("CANCEL_CNT,");
sb.append("0");
sb.append("AS");
sb.append("CANCEL_QTY,");
sb.append("0");
sb.append("AS");
sb.append("CANCEL_AMT,");
sb.append("0");
sb.append("AS");
sb.append("RETURN_CNT,");
sb.append("0");
sb.append("AS");
sb.append("RETURN_QTY,");
sb.append("0");
sb.append("AS");
sb.append("RETURN_AMT,");
sb.append("0");
sb.append("AS");
sb.append("RETURN_CAN_CNT,");
sb.append("0");
sb.append("AS");
sb.append("RETURN_CAN_QTY,");
sb.append("0");
sb.append("AS");
sb.append("RETURN_CAN_AMT,");
sb.append("0");
sb.append("AS");
sb.append("EXCH_CNT,");
sb.append("0");
sb.append("AS");
sb.append("EXCH_CAN_CNT,");
sb.append("0");
sb.append("AS");
sb.append("AS_CNT,");
sb.append("0");
sb.append("AS");
sb.append("COUNSEL_CNT,");
sb.append("0");
sb.append("AS");
sb.append("COUNSEL_PROC_CNT,");
sb.append("0");
sb.append("AS");
sb.append("QUESTION_CNT,");
sb.append("COUNT(B.CUST_NO)");
sb.append("AS");
sb.append("OB_ALLOC_CNT,");
sb.append("0");
sb.append("AS");
sb.append("OB_PROC_CNT,");
sb.append("0");
sb.append("AS");
sb.append("OB_NOPROC_CNT");
sb.append("FROM");
sb.append("TOBCUSTM");
sb.append("B,");
sb.append("TOBCODE");
sb.append("A");
sb.append("WHERE");
sb.append("A.OB_GB");
sb.append("=");
sb.append("B.OB_GB");
sb.append("AND");
sb.append("A.OB_SEQ");
sb.append("=");
sb.append("B.OB_SEQ");
sb.append("AND");
sb.append("B.TM_ID");
sb.append("=");
sb.append("'user_id'");
sb.append("AND");
sb.append("A.DISTR_DATE");
sb.append("<![CDATA[>=]]>");
sb.append("TO_DATE('2014-01-01','yyyy/mm/dd')");
sb.append("AND");
sb.append("A.DISTR_DATE");
sb.append("<![CDATA[<");
sb.append("]]>");
sb.append("TO_DATE('2014-01-01','yyyy/mm/dd')");
sb.append("+");
sb.append("1");
sb.append("UNION");
sb.append("ALL");
sb.append("SELECT");
sb.append("0");
sb.append("AS");
sb.append("ORDER_CNT,");
sb.append("0");
sb.append("AS");
sb.append("ORDER_QTY,");
sb.append("0");
sb.append("AS");
sb.append("ORDER_AMT,");
sb.append("0");
sb.append("AS");
sb.append("CANCEL_CNT,");
sb.append("0");
sb.append("AS");
sb.append("CANCEL_QTY,");
sb.append("0");
sb.append("AS");
sb.append("CANCEL_AMT,");
sb.append("0");
sb.append("AS");
sb.append("RETURN_CNT,");
sb.append("0");
sb.append("AS");
sb.append("RETURN_QTY,");
sb.append("0");
sb.append("AS");
sb.append("RETURN_AMT,");
sb.append("0");
sb.append("AS");
sb.append("RETURN_CAN_CNT,");
sb.append("0");
sb.append("AS");
sb.append("RETURN_CAN_QTY,");
sb.append("0");
sb.append("AS");
sb.append("RETURN_CAN_AMT,");
sb.append("0");
sb.append("AS");
sb.append("EXCH_CNT,");
sb.append("0");
sb.append("AS");
sb.append("EXCH_CAN_CNT,");
sb.append("0");
sb.append("AS");
sb.append("AS_CNT,");
sb.append("0");
sb.append("AS");
sb.append("COUNSEL_CNT,");
sb.append("0");
sb.append("AS");
sb.append("COUNSEL_PROC_CNT,");
sb.append("0");
sb.append("AS");
sb.append("QUESTION_CNT,");
sb.append("0");
sb.append("AS");
sb.append("OB_ALLOC_CNT,");
sb.append("COUNT(DISTINCT");
sb.append("A.OB_GB||A.OB_SEQ||A.SELECT_SEQ||TO_CHAR(A.PROC_DATE,'YYYYMMDD'))");
sb.append("AS");
sb.append("OB_PROC_CNT,");
sb.append("0");
sb.append("AS");
sb.append("OB_NOPROC_CNT");
sb.append("FROM");
sb.append("TOBCUSTDT");
sb.append("A");
sb.append("WHERE");
sb.append("1=1");
sb.append("AND");
sb.append("A.PROC_ID");
sb.append("=");
sb.append("'user_id'");
sb.append("AND");
sb.append("A.PROC_DATE");
sb.append("<![CDATA[>=]]>");
sb.append("TO_DATE('2014-01-01','yyyy/mm/dd')");
sb.append("AND");
sb.append("A.PROC_DATE");
sb.append("<![CDATA[<");
sb.append("]]>");
sb.append("TO_DATE('2014-01-01','yyyy/mm/dd')");
sb.append("+");
sb.append("1");
sb.append("UNION");
sb.append("ALL");
sb.append("SELECT");
sb.append("0");
sb.append("AS");
sb.append("ORDER_CNT,");
sb.append("0");
sb.append("AS");
sb.append("ORDER_QTY,");
sb.append("0");
sb.append("AS");
sb.append("ORDER_AMT,");
sb.append("0");
sb.append("AS");
sb.append("CANCEL_CNT,");
sb.append("0");
sb.append("AS");
sb.append("CANCEL_QTY,");
sb.append("0");
sb.append("AS");
sb.append("CANCEL_AMT,");
sb.append("0");
sb.append("AS");
sb.append("RETURN_CNT,");
sb.append("0");
sb.append("AS");
sb.append("RETURN_QTY,");
sb.append("0");
sb.append("AS");
sb.append("RETURN_AMT,");
sb.append("0");
sb.append("AS");
sb.append("RETURN_CAN_CNT,");
sb.append("0");
sb.append("AS");
sb.append("RETURN_CAN_QTY,");
sb.append("0");
sb.append("AS");
sb.append("RETURN_CAN_AMT,");
sb.append("0");
sb.append("AS");
sb.append("EXCH_CNT,");
sb.append("0");
sb.append("AS");
sb.append("EXCH_CAN_CNT,");
sb.append("0");
sb.append("AS");
sb.append("AS_CNT,");
sb.append("0");
sb.append("AS");
sb.append("COUNSEL_CNT,");
sb.append("0");
sb.append("AS");
sb.append("COUNSEL_PROC_CNT,");
sb.append("0");
sb.append("AS");
sb.append("QUESTION_CNT,");
sb.append("0");
sb.append("AS");
sb.append("OB_ALLOC_CNT,");
sb.append("0");
sb.append("AS");
sb.append("OB_PROC_CNT,");
sb.append("COUNT('X')");
sb.append("AS");
sb.append("OB_NOPROC_CNT");
sb.append("FROM");
sb.append("TOBCUSTM");
sb.append("A");
sb.append("WHERE");
sb.append("1=1");
sb.append("AND");
sb.append("A.TM_ID");
sb.append("=");
sb.append("'user_id'");
sb.append("AND");
sb.append("A.DO_FLAG");
sb.append("=");
sb.append("'10'");
sb.append(";");
//String fsql = data.makeSql();
//gSqlContainer sumber=new gSqlContainer();
MHorizontalLayout sidebar = new MHorizontalLayout();
MHorizontalLayout isicontents=new MHorizontalLayout();
MHorizontalLayout toolbar = new MHorizontalLayout();
toolbar.addComponent(new CheckBox("Indv.Query"));
//TabSheet tabsheet = new TabSheet();
//-------------------- Header  ------------------------------
toolbar.addComponent(new TextField("Proc. Person"));
toolbar.addComponent(new TextField(""));
toolbar.addComponent(new PopupDateField("Entry Day"));
toolbar.addComponent(new PopupDateField("~"));


//-------------------- Header  ------------------------------
MHorizontalLayout toolmenu;
toolmenu = new MHorizontalLayout();
toolmenu.addComponent(new Button("Ret"));
toolmenu.addComponent(new Button("Ins"));
toolmenu.addComponent(new Button("Del"));
toolmenu.addComponent(new Button("Save"));
toolmenu.addComponent(new Button("Print"));
toolmenu.addComponent(new Button("XLS"));
        addComponents(
                new Header("Agent Work Record (MyWorkList)"
        ));
        addComponents(toolmenu);
        addComponents(toolbar);
        addComponents(isicontents);
MTable table=new MTable();
//-------------------- Header Table ---judul untuk table----------
table.addContainerProperty("No", String.class,  null);
table.addContainerProperty("ITEM", String.class,  null);
table.addContainerProperty("No", String.class,  null);
//-------------------- Header Table ------------------------------
   isicontents.addComponents(table);
        addLayoutClickListener(new LayoutEvents.LayoutClickListener() {
            @Override
            public void layoutClick(LayoutEvents.LayoutClickEvent event) {
            }
        });
    }
    @Override
    public void enter(ViewChangeListener.ViewChangeEvent event) {
    }
}
