package com.dartmedia.felino.form;
import com.cware.back.common.BaseEntity;
import com.dartmedia.felino.gSqlContainer;
import com.dartmedia.felino.fgetsql;
import com.dartmedia.felino.gSqlContainer;
import com.vaadin.cdi.CDIView;
import com.vaadin.data.fieldgroup.BeanFieldGroup;
import org.vaadin.maddon.fields.MTable;
import com.vaadin.event.LayoutEvents;
import org.vaadin.maddon.layouts.MHorizontalLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.TextField;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.DateField;
import com.vaadin.ui.Notification;
import com.vaadin.ui.PopupDateField;
import com.vaadin.ui.TreeTable;
import com.vaadin.navigator.View;
import com.vaadin.ui.RichTextArea;
import com.vaadin.navigator.ViewChangeListener;
import com.vaadin.data.util.sqlcontainer.SQLContainer;
import com.vaadin.data.util.sqlcontainer.connection.SimpleJDBCConnectionPool;
import com.vaadin.data.util.sqlcontainer.query.FreeformQuery;
import javax.annotation.PostConstruct;
import javax.inject.Inject;
import java.util.List;
import java.sql.SQLException;
import org.vaadin.maddon.label.Header;
import org.vaadin.maddon.fields.MTable;
import org.vaadin.maddon.fields.MValueChangeEvent;
import org.vaadin.maddon.fields.MValueChangeListener;
import org.vaadin.maddon.layouts.MVerticalLayout;
@CDIView("OrderDetailsList")
public class OrderDetailsListView extends MVerticalLayout implements View {
//OrderDetailsListSvc data=new OrderDetailsListSvc();
//@Inject   TenterpriseFacade cf;
//@Inject  TenterpriseForm form;
    @PostConstruct
    public void initComponent() {
/****/
StringBuffer sb = new StringBuffer();
StringBuffer sb1 = new StringBuffer();
sb.append("SELECT");
sb.append("/*");
sb.append("orderreport.xml");
sb.append(":");
sb.append("custcenter.orderreport.selectOrderDetailsCancel");
sb.append("by");
sb.append("OrderDetailsList");
sb.append("*/");
sb.append("A.ORDER_NO");
sb.append("AS");
sb.append("ORDER_NO,");
sb.append("A.CANCEL_GB");
sb.append("AS");
sb.append("ORDER_GB,");
sb.append("A.DO_FLAG");
sb.append("AS");
sb.append("DO_FLAG,");
sb.append("TO_CHAR(A.CANCEL_DATE,");
sb.append("'YYYY/MM/DD')");
sb.append("AS");
sb.append("ORDER_DATE,");
sb.append("TO_CHAR(A.LAST_PROC_DATE,'YYYY/MM/DD')");
sb.append("AS");
sb.append("OK_DATE,");
sb.append("A.GOODS_CODE");
sb.append("AS");
sb.append("GOODS_CODE,");
sb.append("C.GOODS_NAME");
sb.append("AS");
sb.append("GOODS_NAME,");
sb.append("A.GOODSDT_CODE");
sb.append("AS");
sb.append("GOODSDT_CODE,");
sb.append("C.GOODSDT_INFO");
sb.append("AS");
sb.append("GOODSDT_INFO,");
sb.append("A.CANCEL_QTY");
sb.append("AS");
sb.append("ORDER_QTY,");
sb.append("A.RSALE_AMT");
sb.append("AS");
sb.append("ORDER_AMT,");
sb.append("A.CANCEL_QTY");
sb.append("AS");
sb.append("SYSLAST,");
sb.append("A.RSALE_AMT");
sb.append("AS");
sb.append("SYSLAST_AMT,");
sb.append("G.CUST_NO");
sb.append("AS");
sb.append("CUST_NO,");
sb.append("D.CUST_NAME");
sb.append("AS");
sb.append("CUST_NAME,");
sb.append("F.RECEIVER");
sb.append("AS");
sb.append("RECEIVER,");
sb.append("F.TEL");
sb.append("AS");
sb.append("TEL_NO,");
sb.append("F.RECEIVER_HP");
sb.append("AS");
sb.append("HOB_NO,");
sb.append("FUN_ADD_POSTADDR(F.RECEIVER_POST,F.RECEIVER_POST_SEQ,F.RECEIVER_ADDR)");
sb.append("AS");
sb.append("ADDR");
sb.append("FROM");
sb.append("TCANCELDT");
sb.append("A,");
sb.append("TGOODS");
sb.append("B,");
sb.append("TGOODSDT");
sb.append("C,");
sb.append("TCUSTOMER");
sb.append("D,");
sb.append("TRECEIVER");
sb.append("F,");
sb.append("TORDERM");
sb.append("G,");
sb.append("TORDERPROC");
sb.append("H");
sb.append("WHERE");
sb.append("A.GOODS_CODE");
sb.append("=");
sb.append("B.GOODS_CODE");
sb.append("AND");
sb.append("A.GOODS_CODE");
sb.append("=");
sb.append("C.GOODS_CODE");
sb.append("AND");
sb.append("A.GOODSDT_CODE");
sb.append("=");
sb.append("C.GOODSDT_CODE");
sb.append("AND");
sb.append("A.CUST_NO");
sb.append("=");
sb.append("D.CUST_NO");
sb.append("AND");
sb.append("A.CUST_NO");
sb.append("=");
sb.append("F.CUST_NO");
sb.append("AND");
sb.append("A.RECEIVER_SEQ");
sb.append("=");
sb.append("F.RECEIVER_SEQ");
sb.append("AND");
sb.append("A.ORDER_NO");
sb.append("=");
sb.append("G.ORDER_NO");
sb.append("AND");
sb.append("A.ORDER_NO");
sb.append("=");
sb.append("H.ORDER_NO");
sb.append("AND");
sb.append("A.ORDER_G_SEQ");
sb.append("=");
sb.append("H.ORDER_G_SEQ");
sb.append("AND");
sb.append("A.ORDER_D_SEQ");
sb.append("=");
sb.append("H.ORDER_D_SEQ");
sb.append("AND");
sb.append("A.ORDER_W_SEQ");
sb.append("=");
sb.append("H.ORDER_W_SEQ");
sb.append("AND");
sb.append("H.PROC_DATE");
sb.append(">=");
sb.append("TO_DATE('2014-01-01',");
sb.append("'YYYY/MM/DD')");
sb.append("/*");
sb.append("fromDate");
sb.append("*/");
sb.append("AND");
sb.append("H.PROC_DATE");
sb.append("<");
sb.append("TO_DATE('2014-01-01',");
sb.append("'YYYY/MM/DD')");
sb.append("+");
sb.append("1");
sb.append("/*");
sb.append("toDate");
sb.append("*/");
sb.append("AND");
sb.append("H.DO_FLAG");
sb.append("=");
sb.append("'query_gb'");
sb.append("/*");
sb.append("query_gb");
sb.append("*/");
sb.append("AND");
sb.append("A.DO_FLAG");
sb.append("LIKE");
sb.append("'proc_step'");
sb.append("||");
sb.append("'%'");
sb.append("/*");
sb.append("proc_step");
sb.append("*/");
sb.append("AND");
sb.append("A.GOODS_CODE");
sb.append("LIKE");
sb.append("'goods_code'");
sb.append("||");
sb.append("'%'");
sb.append("/*");
sb.append("goods_code");
sb.append("*/");
sb.append("AND");
sb.append("B.ENTP_CODE");
sb.append("LIKE");
sb.append("'entp_code'");
sb.append("||");
sb.append("'%'");
sb.append("/*");
sb.append("entp_code");
sb.append("*/");
sb.append("ORDER");
sb.append("BY");
sb.append("A.ORDER_NO");
sb.append("SELECT");
sb.append("/*");
sb.append("orderreport.xml");
sb.append(":");
sb.append("custcenter.orderreport.selectOrderDetailsClaim");
sb.append("by");
sb.append("OrderDetailsList");
sb.append("*/");
sb.append("A.ORDER_NO");
sb.append("AS");
sb.append("ORDER_NO,");
sb.append("A.CLAIM_GB");
sb.append("AS");
sb.append("ORDER_GB,");
sb.append("A.DO_FLAG");
sb.append("AS");
sb.append("DO_FLAG,");
sb.append("TO_CHAR(A.CLAIM_DATE,");
sb.append("'YYYY/MM/DD')");
sb.append("AS");
sb.append("ORDER_DATE,");
sb.append("<choose>");
sb.append("<when");
sb.append("test='flag");
sb.append("==");
//sb.append(""40"'>");
sb.append("FUN_GET_PROC_DATE(A.ORDER_NO,A.ORDER_G_SEQ,A.ORDER_D_SEQ,A.ORDER_W_SEQ,'40')");
sb.append("AS");
sb.append("ORDER_OUT_DATE,");
sb.append("FUN_GET_PROC_DATE(A.ORDER_NO,A.ORDER_G_SEQ,A.ORDER_D_SEQ,A.ORDER_W_SEQ,'80')");
sb.append("AS");
sb.append("DELY_DATE,");
sb.append("</when>");
sb.append("<otherwise>");
sb.append("FUN_GET_PROC_DATE(A.ORDER_NO,A.ORDER_G_SEQ,A.ORDER_D_SEQ,A.ORDER_W_SEQ,'60')");
sb.append("AS");
sb.append("RET_DATE,");
sb.append("</otherwise>");
sb.append("</choose>");
sb.append("A.GOODS_CODE");
sb.append("AS");
sb.append("GOODS_CODE,");
sb.append("C.GOODS_NAME");
sb.append("AS");
sb.append("GOODS_NAME,");
sb.append("A.GOODSDT_CODE");
sb.append("AS");
sb.append("GOODSDT_CODE,");
sb.append("C.GOODSDT_INFO");
sb.append("AS");
sb.append("GOODSDT_INFO,");
sb.append("A.CLAIM_QTY");
sb.append("AS");
sb.append("ORDER_QTY,");
sb.append("A.RSALE_AMT");
sb.append("AS");
sb.append("ORDER_AMT,");
sb.append("A.SYSLAST");
sb.append("AS");
sb.append("SYSLAST,");
sb.append("A.SYSLAST_AMT");
sb.append("AS");
sb.append("SYSLAST_AMT,");
sb.append("G.CUST_NO");
sb.append("AS");
sb.append("CUST_NO,");
sb.append("D.CUST_NAME");
sb.append("AS");
sb.append("CUST_NAME,");
sb.append("F.RECEIVER");
sb.append("AS");
sb.append("RECEIVER,");
sb.append("F.TEL");
sb.append("AS");
sb.append("TEL_NO,");
sb.append("F.RECEIVER_HP");
sb.append("AS");
sb.append("HOB_NO,");
sb.append("FUN_ADD_POSTADDR(F.RECEIVER_POST,F.RECEIVER_POST_SEQ,F.RECEIVER_ADDR)");
sb.append("AS");
sb.append("ADDR");
sb.append("FROM");
sb.append("TCLAIMDT");
sb.append("A,");
sb.append("TGOODS");
sb.append("B,");
sb.append("TGOODSDT");
sb.append("C,");
sb.append("TCUSTOMER");
sb.append("D,");
sb.append("TRECEIVER");
sb.append("F,");
sb.append("TORDERM");
sb.append("G,");
sb.append("TORDERPROC");
sb.append("H");
sb.append("WHERE");
sb.append("A.GOODS_CODE");
sb.append("=");
sb.append("B.GOODS_CODE");
sb.append("AND");
sb.append("A.GOODS_CODE");
sb.append("=");
sb.append("C.GOODS_CODE");
sb.append("AND");
sb.append("A.GOODSDT_CODE");
sb.append("=");
sb.append("C.GOODSDT_CODE");
sb.append("AND");
sb.append("A.CUST_NO");
sb.append("=");
sb.append("D.CUST_NO");
sb.append("AND");
sb.append("A.CUST_NO");
sb.append("=");
sb.append("F.CUST_NO");
sb.append("AND");
sb.append("A.RECEIVER_SEQ");
sb.append("=");
sb.append("F.RECEIVER_SEQ");
sb.append("AND");
sb.append("A.ORDER_NO");
sb.append("=");
sb.append("G.ORDER_NO");
sb.append("AND");
sb.append("A.ORDER_NO");
sb.append("=");
sb.append("H.ORDER_NO");
sb.append("AND");
sb.append("A.ORDER_G_SEQ");
sb.append("=");
sb.append("H.ORDER_G_SEQ");
sb.append("AND");
sb.append("A.ORDER_D_SEQ");
sb.append("=");
sb.append("H.ORDER_D_SEQ");
sb.append("AND");
sb.append("A.ORDER_W_SEQ");
sb.append("=");
sb.append("H.ORDER_W_SEQ");
sb.append("AND");
sb.append("H.PROC_DATE");
sb.append(">=");
sb.append("TO_DATE('2014-01-01',");
sb.append("'YYYY/MM/DD')");
sb.append("/*");
sb.append("fromDate");
sb.append("*/");
sb.append("AND");
sb.append("H.PROC_DATE");
sb.append("<");
sb.append("TO_DATE('2014-01-01',");
sb.append("'YYYY/MM/DD')");
sb.append("+");
sb.append("1");
sb.append("/*");
sb.append("toDate");
sb.append("*/");
sb.append("AND");
sb.append("H.DO_FLAG");
sb.append("=");
sb.append("'query_gb'");
sb.append("/*");
sb.append("query_gb");
sb.append("*/");
sb.append("AND");
sb.append("A.DO_FLAG");
sb.append("LIKE");
sb.append("'proc_step'");
sb.append("||");
sb.append("'%'");
sb.append("/*");
sb.append("proc_step");
sb.append("*/");
sb.append("AND");
sb.append("A.GOODS_CODE");
sb.append("LIKE");
sb.append("'goods_code'");
sb.append("||");
sb.append("'%'");
sb.append("/*");
sb.append("goods_code");
sb.append("*/");
sb.append("AND");
sb.append("B.ENTP_CODE");
sb.append("LIKE");
sb.append("'entp_code'");
sb.append("||");
sb.append("'%'");
sb.append("/*");
sb.append("entp_code");
sb.append("*/");
sb.append("AND");
sb.append("A.CLAIM_GB");
sb.append("=");
sb.append("'flag'");
sb.append("/*");
sb.append("flag");
sb.append("*/");
sb.append("ORDER");
sb.append("BY");
sb.append("A.ORDER_NO");
//String fsql = data.makeSql();
//gSqlContainer sumber=new gSqlContainer();
MHorizontalLayout sidebar = new MHorizontalLayout();
MHorizontalLayout isicontents=new MHorizontalLayout();
MHorizontalLayout toolbar = new MHorizontalLayout();
toolbar.addComponent(new CheckBox("Indv.Query"));
//TabSheet tabsheet = new TabSheet();
//-------------------- Header  ------------------------------
toolbar.addComponent(new PopupDateField("Term"));
toolbar.addComponent(new PopupDateField("MD"));
toolbar.addComponent(new CheckBox("Indv.Query"));


//-------------------- Header  ------------------------------
MHorizontalLayout toolmenu;
toolmenu = new MHorizontalLayout();
toolmenu.addComponent(new Button("Ret"));
toolmenu.addComponent(new Button("Ins"));
toolmenu.addComponent(new Button("Del"));
toolmenu.addComponent(new Button("Save"));
toolmenu.addComponent(new Button("Print"));
toolmenu.addComponent(new Button("XLS"));
        addComponents(
                new Header("Order Report (OrderDetailsList)"
        ));
        addComponents(toolmenu);
        addComponents(toolbar);
//        addComponents(isicontents);
//MTable table=new MTable();
//-------------------- Header Table ---judul untuk table----------
//List<Tenterprise> findAll = cf.findAll();
//MTable<Tenterprise> table=new MTable<Tenterprise>(Tenterprise.class).withProperties("entpName");
//table.setBeans(findAll);
//table.addMValueChangeListener(new MValueChangeListener<Tdescribecode>() {
//    @Override
//    public void valueChange(MValueChangeEvent<Tdescribecode> event) {
//    Notification.show("ss");
//    form.setEntity(event.getValue());
//    }
//    });
//table.addContainerProperty("No", String.class,  null);
//-------------------- Header Table ------------------------------
//   isicontents.addComponents(table);
try{
            SimpleJDBCConnectionPool connectionPool = new SimpleJDBCConnectionPool(
             "oracle.jdbc.OracleDriver",BaseEntity.jdbc,
             "dartmedia", "dartmedia",2,5);
             SQLContainer container;
              container = new SQLContainer(new FreeformQuery(
              sb.toString(),connectionPool,"AD_MENU_ID"));
             // MTable table= new MTable("MENU",container);
               MTable table = new MTable();
               table.setContainerDataSource(container);
table.addMValueChangeListener(new MValueChangeListener() {
    @Override
    public void valueChange(MValueChangeEvent event) {
    Notification.show("ss");
//    form.setEntity(event.getValue());
    }
   });
              addComponents(table);
 } catch (SQLException e) {
     e.printStackTrace();
     RichTextArea rtarea = new RichTextArea();
     rtarea.setValue(sb.toString());
      addComponents(rtarea);
}
        addLayoutClickListener(new LayoutEvents.LayoutClickListener() {
            @Override
            public void layoutClick(LayoutEvents.LayoutClickEvent event) {
            }
        });
    }
    @Override
    public void enter(ViewChangeListener.ViewChangeEvent event) {
    }
}
