package com.dartmedia.felino.form;
import com.dartmedia.felino.gSqlContainer;
import com.dartmedia.felino.fgetsql;
import com.dartmedia.felino.gSqlContainer;
import com.vaadin.cdi.CDIView;
import com.vaadin.data.fieldgroup.BeanFieldGroup;
import org.vaadin.maddon.fields.MTable;
import com.vaadin.event.LayoutEvents;
import org.vaadin.maddon.layouts.MHorizontalLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.TextField;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.ComboBox;
import com.vaadin.ui.DateField;
import com.vaadin.ui.PopupDateField;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener;
import com.vaadin.data.util.sqlcontainer.query.FreeformQuery;
import javax.annotation.PostConstruct;
import org.vaadin.maddon.label.Header;
import org.vaadin.maddon.layouts.MVerticalLayout;
@CDIView("WhTransferSearch")
public class WhTransferSearchView extends MVerticalLayout implements View {
//WhTransferSearchSvc data=new WhTransferSearchSvc();
    @PostConstruct
    public void initComponent() {
// @Inject
//TbrandForm form;
/**Move out no <p:inputText></p:inputText>Inquiry <p:selectOneListbox>  </p:selectOneListbox>Term <p:calendar></p:calendar>Proc step     <p:selectOneListbox>  </p:selectOneListbox>                         Shipment warehouse <p:selectOneListbox>  </p:selectOneListbox>   Item code  <p:inputText></p:inputText> Receipt warehouse <p:selectOneListbox></p:selectOneListbox>                   **/
StringBuffer sb = new StringBuffer();
sb.append("SELECT");
sb.append("/*");
sb.append("warehousemove.xml");
sb.append(":");
sb.append("logistics.warehousemove.selectWhTransferSearch");
sb.append("by");
sb.append("WhTransferSearch");
sb.append("*/");
sb.append("OM.MOVE_OUT_SEQ,");
sb.append("IM.MOVE_IN_SEQ,");
sb.append("OM.WH_IN_CODE,");
sb.append("OM.WH_OUT_CODE,");
sb.append("OM.DO_FLAG,");
sb.append("TO_CHAR(OM.REQUEST_DATE,");
sb.append("'YYYY/MM/DD')");
sb.append("AS");
sb.append("REQUEST_DATE,");
sb.append("TO_CHAR(OM.OUT_DATE,");
sb.append("'YYYY/MM/DD')");
sb.append("AS");
sb.append("OUT_DATE,");
sb.append("TO_CHAR(IM.IN_DATE,");
sb.append("'YYYY/MM/DD')");
sb.append("AS");
sb.append("IN_DATE,");
sb.append("TO_CHAR(OM.CANCEL_DATE,");
sb.append("'YYYY/MM/DD')");
sb.append("AS");
sb.append("CANCEL_DATE,");
sb.append("OM.REQUEST_REASON,");
sb.append("OM.CANCEL_REASON");
sb.append("FROM");
sb.append("TWHMOVEOUTM");
sb.append("OM,");
sb.append("TWHMOVEINM");
sb.append("IM,");
sb.append("TWHMOVEOUTDT");
sb.append("OT");
sb.append("WHERE");
sb.append("OM.MOVE_OUT_SEQ");
sb.append("=");
sb.append("IM.MOVE_OUT_SEQ(+)");
sb.append("AND");
sb.append("OM.MOVE_OUT_SEQ");
sb.append("=");
sb.append("OT.MOVE_OUT_SEQ(+)");
sb.append("AND");
sb.append("OT.GOODS_CODE");
sb.append("LIKE");
sb.append("'%%'");
sb.append("AND");
sb.append("OM.REQUEST_DATE");
sb.append(">=");
sb.append("TO_DATE('2013/11/01',");
sb.append("'YYYY/MM/DD')");
sb.append("AND");
sb.append("OM.REQUEST_DATE");
sb.append("<=");
sb.append("TO_DATE('2013/11/05',");
sb.append("'YYYY/MM/DD')");
sb.append("AND");
sb.append("OM.WH_OUT_CODE");
sb.append("=");
sb.append("'001'");
sb.append("/*");
sb.append("KALAU");
sb.append("DIBAWAH");
sb.append("INI");
sb.append("DIPAKAI,");
sb.append("TIGA");
sb.append("BARIS");
sb.append("DIATAS");
sb.append("DIHAPUS!");
sb.append("<choose>");
sb.append("<when");
sb.append("test='query_gb");
sb.append("==");
//sb.append(""10"'>");
sb.append("<![CDATA[");
sb.append("AND");
sb.append("OM.REQUEST_DATE");
sb.append(">=");
sb.append("TO_DATE(#{request_date_fr,");
sb.append("jdbcType=VARCHAR},");
sb.append("'YYYY/MM/DD')");
sb.append("AND");
sb.append("OM.REQUEST_DATE");
sb.append("<=");
sb.append("TO_DATE(#{request_date_to,");
sb.append("jdbcType=VARCHAR},");
sb.append("'YYYY/MM/DD')");
sb.append("]]>");
sb.append("</when>");
sb.append("<when");
sb.append("test='query_gb");
sb.append("==");
//sb.append(""40"'>");
sb.append("<![CDATA[");
sb.append("AND");
sb.append("OM.OUT_DATE");
sb.append(">=");
sb.append("TO_DATE(#{request_date_fr,");
sb.append("jdbcType=VARCHAR},");
sb.append("'YYYY/MM/DD')");
sb.append("AND");
sb.append("OM.OUT_DATE");
sb.append("<=");
sb.append("TO_DATE(#{request_date_to,");
sb.append("jdbcType=VARCHAR},");
sb.append("'YYYY/MM/DD')");
sb.append("]]>");
sb.append("</when>");
sb.append("<when");
sb.append("test='query_gb");
sb.append("==");
//sb.append(""50"'>");
sb.append("<![CDATA[");
sb.append("AND");
sb.append("IM.IN_DATE");
sb.append(">=");
sb.append("TO_DATE(#{request_date_fr,");
sb.append("jdbcType=VARCHAR},");
sb.append("'YYYY/MM/DD')");
sb.append("AND");
sb.append("IM.IN_DATE");
sb.append("<=");
sb.append("TO_DATE(#{request_date_to,");
sb.append("jdbcType=VARCHAR},");
sb.append("'YYYY/MM/DD')");
sb.append("]]>");
sb.append("</when>");
sb.append("<otherwise>");
sb.append("<![CDATA[");
sb.append("AND");
sb.append("OM.CANCEL_DATE");
sb.append(">=");
sb.append("TO_DATE(#{request_date_fr,");
sb.append("jdbcType=VARCHAR},");
sb.append("'YYYY/MM/DD')");
sb.append("AND");
sb.append("OM.CANCEL_DATE");
sb.append("<=");
sb.append("TO_DATE(#{request_date_to,");
sb.append("jdbcType=VARCHAR},");
sb.append("'YYYY/MM/DD')");
sb.append("]]>");
sb.append("</otherwise>");
sb.append("</choose>");
sb.append("<if");
//sb.append("test="do_flag");
//sb.append("= ''">");
sb.append("                <if test='do_flag ");
sb.append("=");
//sb.append(""10"'>");
sb.append("AND");
sb.append("OM.DO_FLAG");
sb.append("=");
sb.append("#{do_flag,");
sb.append("jdbcType=VARCHAR}");
sb.append("</if>");
sb.append("<if");
sb.append("test='do_flag");
sb.append("==");
//sb.append(""10"'>");
sb.append("AND");
sb.append("OM.DO_FLAG");
sb.append("IN");
sb.append("(#{do_flag,");
sb.append("jdbcType=VARCHAR},'15')");
sb.append("</if>");
sb.append("</if>");
sb.append("<if");
//sb.append("test="wh_code_out");
//sb.append("= ''">");
sb.append("                AND OM.WH_OUT_CODE = #{wh_code_out, jdbcType=VARCHAR}");
sb.append("            </if>");
//sb.append("            <if test="wh_code_in ");
sb.append("=");
//sb.append("''">");
sb.append("AND");
sb.append("OM.WH_IN_CODE");
sb.append("=");
sb.append("#{wh_code_in,");
sb.append("jdbcType=VARCHAR}");
sb.append("</if>");
sb.append("*/");
sb.append("SELECT");
sb.append("/*");
sb.append("warehousemove.xml");
sb.append(":");
sb.append("logistics.warehousemove.selectWhTransferSearchDetail");
sb.append("by");
sb.append("WhTransferSearch");
sb.append("*/");
sb.append("OD.GOODS_CODE,");
sb.append("OD.GOODSDT_CODE,");
sb.append("G.GOODS_NAME,");
sb.append("G.GOODSDT_INFO,");
sb.append("OD.REQUEST_AQTY,");
sb.append("OD.REQUEST_BQTY,");
sb.append("NVL(OD.OUT_AQTY,");
sb.append("0)");
sb.append("AS");
sb.append("OUT_AQTY,");
sb.append("NVL(OD.OUT_BQTY,");
sb.append("0)");
sb.append("AS");
sb.append("OUT_BQTY,");
sb.append("NVL(ID.IN_AQTY");
sb.append(",");
sb.append("0)");
sb.append("AS");
sb.append("IN_AQTY,");
sb.append("NVL(ID.IN_BQTY");
sb.append(",");
sb.append("0)");
sb.append("AS");
sb.append("IN_BQTY,");
sb.append("OD.MOVE_OUT_SEQ");
sb.append("FROM");
sb.append("TWHMOVEOUTDT");
sb.append("OD,");
sb.append("TGOODSDT");
sb.append("G,");
sb.append("(");
sb.append("SELECT");
sb.append("AA.GOODS_CODE,");
sb.append("AA.GOODSDT_CODE,");
sb.append("AA.MOVE_IN_SEQ,");
sb.append("SUM(AA.IN_AQTY)");
sb.append("AS");
sb.append("IN_AQTY,");
sb.append("SUM(AA.IN_BQTY)");
sb.append("AS");
sb.append("IN_BQTY,");
sb.append("BB.MOVE_OUT_SEQ");
sb.append("FROM");
sb.append("TWHMOVEINDT");
sb.append("AA,");
sb.append("TWHMOVEINM");
sb.append("BB");
sb.append("WHERE");
sb.append("AA.MOVE_IN_SEQ");
sb.append("=");
sb.append("BB.MOVE_IN_SEQ");
sb.append("AND");
sb.append("BB.MOVE_IN_SEQ");
sb.append("=");
sb.append("201311010001");
sb.append("GROUP");
sb.append("BY");
sb.append("AA.GOODS_CODE,");
sb.append("AA.GOODSDT_CODE,");
sb.append("AA.MOVE_IN_SEQ,");
sb.append("BB.MOVE_OUT_SEQ");
sb.append(")");
sb.append("ID");
sb.append("WHERE");
sb.append("OD.MOVE_OUT_SEQ");
sb.append("=");
sb.append("Id.MOVE_OUT_SEQ(+)");
sb.append("AND");
sb.append("OD.GOODS_CODE");
sb.append("=");
sb.append("G.GOODS_CODE");
sb.append("AND");
sb.append("OD.GOODSDT_CODE");
sb.append("=");
sb.append("G.GOODSDT_CODE");
sb.append("AND");
sb.append("ID.GOODS_CODE(+)");
sb.append("=");
sb.append("OD.GOODS_CODE");
sb.append("AND");
sb.append("ID.GOODSDT_CODE(+)");
sb.append("=");
sb.append("OD.GOODSDT_CODE");
sb.append("AND");
sb.append("OD.MOVE_OUT_SEQ");
sb.append("=");
sb.append("201311010001");
//String fsql = data.makeSql();
//gSqlContainer sumber=new gSqlContainer();
MHorizontalLayout sidebar = new MHorizontalLayout();
MHorizontalLayout isicontents=new MHorizontalLayout();
MHorizontalLayout toolbar = new MHorizontalLayout();
toolbar.addComponent(new CheckBox("Indv.Query"));
//TabSheet tabsheet = new TabSheet();
//-------------------- Header  ------------------------------

//-------------------- Header  ------------------------------
MHorizontalLayout toolmenu;
toolmenu = new MHorizontalLayout();
toolmenu.addComponent(new Button("Ret"));
toolmenu.addComponent(new Button("Ins"));
toolmenu.addComponent(new Button("Del"));
toolmenu.addComponent(new Button("Save"));
toolmenu.addComponent(new Button("Print"));
toolmenu.addComponent(new Button("XLS"));
        addComponents(
                new Header("Wh Transfer Report (WhTransferSearch)"
        ));
        addComponents(toolmenu);
        addComponents(toolbar);
        addComponents(isicontents);
MTable table=new MTable();
//-------------------- Header Table ---judul untuk table----------
table.addContainerProperty("No", String.class,  null);
table.addContainerProperty("ITEM", String.class,  null);
table.addContainerProperty("No", String.class,  null);
//-------------------- Header Table ------------------------------
   isicontents.addComponents(table);
        addLayoutClickListener(new LayoutEvents.LayoutClickListener() {
            @Override
            public void layoutClick(LayoutEvents.LayoutClickEvent event) {
            }
        });
    }
    @Override
    public void enter(ViewChangeListener.ViewChangeEvent event) {
    }
}
